# Phase 4 — Baseline Models
**Capstone 1 | Phases 1–5**

Trains Logistic Regression and linear SVM on the engineered feature set. Establishes the performance floor.

**Results:**
- Logistic Regression: F1 = 0.6447, Accuracy = 0.6460
- SVM: F1 = 0.6095, Accuracy = 0.6094

Both models beat random chance but are limited by the linearity assumption in the 800-feature space.

**Loads:** `outputs/features_baseline.pkl`  
**Next:** `phase5_augmentation_sr.ipynb`


In [ ]:
import numpy as np, random, os
RANDOM_SEED = 42
random.seed(RANDOM_SEED); np.random.seed(RANDOM_SEED)
os.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)
try:
    import torch
    torch.manual_seed(RANDOM_SEED); torch.cuda.manual_seed_all(RANDOM_SEED)
    torch.backends.cudnn.deterministic = True; torch.backends.cudnn.benchmark = False
    print(f"Seeds fixed (numpy + random + torch): {RANDOM_SEED}")
except ImportError:
    print(f"Seeds fixed (numpy + random): {RANDOM_SEED}")
print("Always run this cell first on every restart.")


In [ ]:
import joblib
bundle = joblib.load('outputs/features_baseline.pkl')
X_train = bundle['X_train']; X_test = bundle['X_test']
y_train = bundle['y_train']; y_test = bundle['y_test']
print(f"X_train: {X_train.shape} | X_test: {X_test.shape}")


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# Train Logistic Regression and SVM models
model = LogisticRegression(random_state=42).fit(X_train, y_train)
svm_model = SVC(kernel='linear', random_state=42).fit(X_train, y_train)


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

models = {'Logistic Regression': model, 'SVM': svm_model}

for name, m in models.items():
    y_pred = m.predict(X_test)
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(f"\n{name} Classification Report:\n{classification_report(y_test, y_pred)}")
    print(f"{name} Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n{'-'*50}\n")


Logistic Regression Accuracy: 0.6460

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.65      0.65       137
           1       0.65      0.64      0.64       137

    accuracy                           0.65       274
   macro avg       0.65      0.65      0.65       274
weighted avg       0.65      0.65      0.65       274

Logistic Regression Confusion Matrix:
[[89 48]
 [49 88]]
--------------------------------------------------

SVM Accuracy: 0.6095

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.59      0.60       137
           1       0.61      0.63      0.62       137

    accuracy                           0.61       274
   macro avg       0.61      0.61      0.61       274
weighted avg       0.61      0.61      0.61       274

SVM Confusion Matrix:
[[81 56]
 [51 86]]
--------------------------------------------------



### Summary
Baseline Model Performance:

Trained and evaluated Logistic Regression and SVM models on this meticulously preprocessed dataset:

Logistic Regression (Baseline): Achieved an Accuracy of 0.6460 and an F1-Score of 0.6447.
SVM (Baseline): Achieved an Accuracy of 0.6095 and an F1-Score of 0.6094.
These baseline results provided a starting point for improvement.